BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "obras_obra" (
	"id"	integer NOT NULL,
	"col_comunidad"	varchar(200) NOT NULL,
	"rubro"	varchar(60) NOT NULL,
	"subclasificacion"	varchar(40) NOT NULL,
	"nombre_obra"	varchar(200) NOT NULL,
	"tenencia"	varchar(30) NOT NULL,
	"modalidad_ejecucion"	varchar(17) NOT NULL,
	"metas_cantidad"	integer unsigned NOT NULL CHECK("metas_cantidad" >= 0),
	"metas_unidad"	varchar(10) NOT NULL,
	"metas_beneficiarios"	integer unsigned NOT NULL CHECK("metas_beneficiarios" >= 0),
	"costo_total"	real NOT NULL,
	"inv_estatal"	real NOT NULL,
	"fism"	real NOT NULL,
	"inv_federal"	real NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (1,'EL AHIJADERO','AGUA POTABLE','RED O SISTEMA DE AGUA ENTUBADA','CONSTRUCCION DE RED DE AGUA ENTUBADA EN MADERO LOCALIDAD DE EL AHIJADERO','EL AHIJADERO','ADMINISTRACION',5,'KM',295,'$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (2,'BALCONES','AGUA POTABLE','RED O SISTEMA DE AGUA ENTUBADA','CONSTRUCCION DE RED DE AGUA ENTUBADA EN MADERO LOCALIDAD DE BALCONES','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',5,'KM',145,'$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (3,'EL ANIL','AGUA POTABLE','RED O SISTEMA DE AGUA ENTUBADA','CONSTRUCCION DE RED DE AGUA ENTUBADA EN MADERO LOCALIDAD DE EL ANIL','AHIJADERO','ADMINISTRACION',1,'KM',58,'$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (4,'LA PALIZADA','AGUA POTABLE','RED O SISTEMA DE AGUA ENTUBADA','EXTENSION DE LINEA DE AGUA POTABLE EN MADERO, LOCALIDAD LA PALIZADA','LA PALIZADA','CONTRATO',177,'MT',259,'$120,000.00',0.0,'$120,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (5,'TURIO','AGUA POTABLE','TANQUE DE AGUA ENTUBADA','CONSTRUCCION DE TANQUE DE ALMACENAMIENTO DE AGUA ENTUBADA EN MADERO LOCALIDAD DE TURIO','SAN DIEGO CURUCUPATZEO','CONTRATO',1,'TANQUE',53,'$700,000.00',0.0,'$700,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (6,'EL DERRUMBADERO','AGUA POTABLE','TANQUE DE AGUA ENTUBADA','CONSTRUCCION DE TANQUE DE ALMACENAMIENTO DE AGUA ENTUBADA EN MADERO LOCALIDAD DE EL DERRUMBADERO','ETUCUARO','CONTRATO',1,'TANQUE',41,'$700,000.00',0.0,'$700,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (7,'PALIZADA','AGUA POTABLE','TANQUE DE AGUA ENTUBADA','CONSTRUCCION DE TANQUE DE ALMACENAMIENTO DE AGUA ENTUBADA EN MADERO LOCALIDAD DE PALIZADA','VILLA MADERO','CONTRATO',1,'TANQUE',259,'$550,000.00',0.0,'$550,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (8,'VILLA MADERO','DRENAJE Y LETRINAS','DRENAJE SANITARIO','REHABILITACION DE DRENAJE SANITARIO EN MADERO LOCALIDAD DE VILLA MADERO COLONIA EL RASTRO AVENIDA INDEPENDENCIA','VILLA MADERO','ADMINISTRACION',800,'ML',200,'$1,500,000.00',0.0,'$1,500,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (9,'SAN DIEGO CURUCUPATZEO','DRENAJE Y LETRINAS','DRENAJE SANITARIO','AMPLIACION DE DRENAJE SANITARIO EN MADERO LOCALIDAD DE SAN DIEGO CURUCUPATZEO CALLE SIN NOMBRE','SAN DIEGO CURUCUPATZEO','CONTRATO',500,'ML',505,'$800,000.00',0.0,'$800,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (10,'VILLA MADERO','DRENAJE Y LETRINAS','DRENAJE SANITARIO','CONSTRUCCION DE DRENAJE SANITARIO EN MADERO  LOCALIDAD DE VILLA MADERO COLONIA CENTRO CALLE PRIVADA MORELOS NORTE','VILLA MADERO','CONTRATO',300,'ML',150,'$700,000.00',0.0,'$700,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (11,'MORENO','DRENAJE Y LETRINAS','DRENAJE PLUVIAL','CONSTRUCCION DE ALCANTARILLAS EN MADERO LOCALIDAD DE MORENO CAMINO MORENO - CAHUATZIO','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',30,'ML',250,'$250,000.00',0.0,'$250,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (12,'PARRITAS (EL AGUACATE)','DRENAJE Y LETRINAS','DRENAJE PLUVIAL','CONSTRUCCION DE ALCANTARILLAS EN MADERO LOCALIDAD DE PARRITAS (EL AGUACATE) CAMINO PARRITAS - EL AGUILA','ETUCUARO','ADMINISTRACION',60,'ML',147,'$350,000.00',0.0,'$350,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (13,'LOS OJOS DE AGUA','DRENAJE Y LETRINAS','DRENAJE PLUVIAL','CONSTRUCCION DE ALCANTARILLAS EN MADERO LOCALIDAD DE LOS OJOS DE AGUA CAMINO OJOS DE AGUA - PIUMO','ETUCUARO','ADMINISTRACION',30,'ML',222,'$250,000.00',0.0,'$250,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (14,'ACATEN','DRENAJE Y LETRINAS','DRENAJE PLUVIAL','CONSTRUCCION DE ALCANTARILLAS EN MADERO LOCALIDAD DE ACATEN CAMINO EL BOSQUE - CERRO BLANCO','ACATEN','ADMINISTRACION',30,'ML',222,'$250,000.00',0.0,'$250,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (15,'VILLA MADERO','DRENAJE Y LETRINAS','DRENAJE PLUVIAL','CONSTRUCCION DE DRENAJE PLUVIAL EN MADERO  LOCALIDAD DE VILLA MADERO COLONIA BUENOS AIRES CALLE NUBE','VILLA MADERO','ADMINISTRACION',500,'ML','1,500.00','$1,200,000.00',0.0,'$1,200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (16,'VILLA MADERO','DRENAJE Y LETRINAS','DRENAJE PLUVIAL','CONSTRUCCION DE DRENAJE PLUVIAL EN MADERO  LOCALIDAD DE VILLA MADERO COLONIA LA CAPICHOLA CALLE SIN NOMBRE','VILLA MADERO','ADMINISTRACION',100,'ML',50,'$300,000.00',0.0,'$300,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (17,'SAN DIEGO CURUCUPATZEO','URBANIZACION','CANCHA','CONSTRUCCION DE CANCHA DEPORTIVA EN  ESCUELA PRIMARIA EN MADERO  LOCALIDAD DE SAN DIEGO CURUCUPATZEO','SAN DIEGO CURUCUPATZEO','CONTRATO',450,'M2',505,'$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (18,'MILPILLAS','URBANIZACION','PUENTE','CONSTRUCCION DE SEGUNDA ETAPA DE PUENTE VEHICULAR EN MADERO LOCALIDAD DE MILPILLAS','SAN DIEGO CURUCUPATZEO','CONTRATO',1,'PUENTE','4,000.00','$2,000,000.00',0.0,'$2,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (19,'LOMA DE CANCHO','URBANIZACION','ANDADOR','AMPLIACION DE ANDADOR EN MADERO LOCALIDAD DE LOMA DE CANCHO CAMINO VILLA MADERO- LOMA DE CANCHO','VILLA MADERO','ADMINISTRACION',400,'ML',213,'$750,000.00',0.0,'$750,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (20,'VILLA MADERO','URBANIZACION','ANDADOR','CONSTRUCCION DE ANDADOR EN MADERO LOCALIDAD DE VILLA MADERO CAMINO VILLA MADERO- PORUAS','VILLA MADERO','ADMINISTRACION',400,'ML',81,'$750,000.00',0.0,'$750,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (21,'PLATANALILLO','URBANIZACION','PAVIMENTACION','AMPLIACION DE PAVIMENTACION CON CARPETA ASFALTICA EN MADERO, LOCALIDAD DE PLATANALILLO CAMINO VILLA MADERO - SAN DIEGO  TRAMO LA CUMBRE - PLATANALILLO','SAN DIEGO CURUCUPATZEO','CONTRATO','3,000.00','M2',136,'$3,300,000.00',0.0,'$3,300,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (22,'ACATEN','URBANIZACION','PAVIMENTACION','AMPLIACION DE PAVIMENTACION CON CARPETA ASFALTICA EN MADERO  LOCALIDAD DE ACATEN','ACATEN','CONTRATO','3,000.00','M2',222,'$3,300,000.00',0.0,'$3,300,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (23,'SANTAS MARIAS','URBANIZACION','PAVIMENTACION','REHABILITACION CON CARPETA ASFALTICA EN MADERO LOCALIDAD DE SANTAS MARIAS TRAMO DEL KM 3+900 AL KM 4+950','ETUCUARO','CONTRATO','1,050.00','ML',223,'$3,600,000.00',0.0,'$3,600,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (24,'VILLA MADERO','URBANIZACION','PARQUE PUBLICO','CONSTRUCCION DE PARQUE PUBLICO EN MADERO LOCALIDAD DE VILLA MADERO COLONIA INFONAVIT','VILLA MADERO','CONTRATO',200,'M2','7,633.00','$500,000.00',0.0,'$500,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (25,'EL CARACOL','URBANIZACION','PAVIMENTACION','CONSTRUCCION DE PAVIMENTACION CON CARPETA ASFALTICA DEL CAMINO E.C VILLA MADERO-LA CUMBRE-EL CARACOL DEL KM 0+000 AL KM 0+500 EN EL MUNICIPIO DE MADERO.ESTADO DE MICHOACAN','EL CARACOL','CONTRATO','3,500.00','M2','1,200.00','$3,934,470.61','$3,934,470.61',0.0,0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (26,'VILLA MADERO','URBANIZACION','PAVIMENTACION','AMPLIACION DE PAVIMENTACION CON CONCRETO HIDRAULICO EN MADERO LOCALIDAD DE VILLA MADERO COLONIA CENTRO AVENIDA ELIAS PEREZ AVALOS','VILLA MADERO','CONTRATO','1,000.00','M2',300,'$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (27,'VILLA MADERO','URBANIZACION','PAVIMENTACION','CONSTRUCCION DE PAVIMENTACION CON CONCRETO HIDRAULICO EN MADERO LOCALIDAD DE VILLA MADERO COLONIA LA PARRITA CALLE SIN NOMBRE','VILLA MADERO','ADMINISTRACION','1,000.00','M2',500,'$800,000.00',0.0,'$800,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (28,'SAN DIEGO CURUCUPATZEO','URBANIZACION','PAVIMENTACION','CONSTRUCCION DE PAVIMENTACION CON ADOQUIN EN MADERO LOCALIDAD DE SAN DIEGO CURUCUPATZEO CALLE SIN NOMBRE','SAN DIEGO CURUCUPATZEO','CONTRATO','1,000.00','M2',505,'$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (29,'EL AHIJADERO','URBANIZACION','REVESTIMIENTO','REVESTIMIENTO DE CAMINO EN MADERO LOCALIDAD DE AHIJADERO TRAMO EL AHIJADERO- CAPULIN','EL AHIJADERO','ADMINISTRACION',25,'KM','1,300.00','$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (30,'EL TEJOCOTE','URBANIZACION','REVESTIMIENTO','REVESTIMIENTO DE CAMINO EN MADERO LOCALIDAD DE EL TEJOCOTE TRAMO EL TEJOCOTE - BALCONES','EL AHIJADERO','ADMINISTRACION',20,'KM','2,000.00','$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (31,'VILLA MADERO','URBANIZACION','ALUMBRADO PUBLICO','AMPLIACION DE ALUMBRADO PUBLICO CON LUMINARIAS LED EN MADERO LOCALIDAD DE VILLA MADERO AVENIDA REVOLUCION','VILLA MADERO','CONTRATO',350,'ML',400,'$1,436,151.58','$1,436,151.58',0.0,0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (32,'VILLA MADERO','URBANIZACION','ALUMBRADO PUBLICO','AMPLIACION DE ALUMBRADO PUBLICO CON LUMINARIAS LED EN ANDADOR VILLA MADERO- LOMA DE CANCHO SEGUNDA ETAPA, LOCALIDAD DE VILLA MADERO','VILLA MADERO','CONTRATO',592,'ML','7,633.00','$1,000,000.00',0.0,'$1,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (33,'VILLA MADERO','URBANIZACION','INFRAESTRUCTURA URBANA','CONSTRUCCION DE TECHADO EN ESPACIO CULTURAL CUATRO CAMINOS EN MADERO LOCALIDAD DE VILLA MADERO','VILLA MADERO','CONTRATO',250,'ML','7,633.00','$1,810,135.73','$1,810,135.73',0.0,0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (34,'LOMA DE SAUZ','URBANIZACION','INFRAESTRUCTURA URBANA','CONSTRUCCION DE PANTEON MUNICIPAL EN MADERO LOCALIDAD DE LOMA DEL SAUZ','VILLA MADERO','CONTRATO',230,'ML','7,633.00','$2,000,000.00',0.0,'$2,000,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (35,'SAN DIEGO CURUCUPATZEO','URBANIZACION','MURO DE CONTENCION','CONSTRUCCION DE MURO DE CONTENCION EN MADERO LOCALIDAD DE SAN DIEGO CURUCUPATZEO','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',59,'ML',505,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (36,'EL GATAL','URBANIZACION','TECHADO','CONSTRUCCION DE TECHADO EN ESPACIO MULTIDEPORTIVO EN MADERO LOCALIDAD DE EL GATAL','ACATEN','CONTRATO',500,'M2',99,'$1,200,000.00',0.0,'$1,200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (37,'CERRO BLANCO','ELECTRIFICACION','ELECTRIFICACION','AMPLIACION DE ELECTRIFICACION EN MADERO LOCALIDAD DE CERRO BLANCO','ACATEN','CONTRATO',500,'ML',82,'$400,000.00',0.0,'$400,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (38,'EL BOSQUE','ELECTRIFICACION','ELECTRIFICACION','AMPLIACION DE ELECTRIFICACION EN MADERO LOCALIDAD DE EL BOSQUE','ACATEN','CONTRATO',100,'ML',83,'$100,000.00',0.0,'$100,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (39,'ACATEN','ELECTRIFICACION','ELECTRIFICACION','AMPLIACION DE ELECTRIFICACION EN MADERO LOCALIDAD DE ACATEN','ACATEN','CONTRATO',100,'ML',84,'$100,000.00',0.0,'$100,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (40,'EL CARGADERO','ELECTRIFICACION','ELECTRIFICACION NO CONVENCIONAL','CONSTRUCCION DE ELECTRIFICACION NO CONVENCIONAL CON PANELES SOLARES EN MADERO LOCALIDAD DE EL CARGADERO','ACATEN','ADMINISTRACION',4,'ACCION',20,'$350,000.00',0.0,'$350,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (41,'RANCHO GRANDE','ELECTRIFICACION','ELECTRIFICACION NO CONVENCIONAL','CONSTRUCCION DE ELECTRIFICACION NO CONVENCIONAL CON PANELES SOLARES EN MADERO LOCALIDAD DE RANCHO GRANDE','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',4,'ACCION',20,'$350,000.00',0.0,'$350,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (42,'CUINDORA','ELECTRIFICACION','ELECTRIFICACION NO CONVENCIONAL','CONSTRUCCION DE ELECTRIFICACION NO CONVENCIONAL CON PANELES SOLARES EN MADERO LOCALIDAD DE LA CUINDORA','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',4,'ACCION',20,'$350,000.00',0.0,'$350,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (43,'LA ALMAZANA','ELECTRIFICACION','ELECTRIFICACION NO CONVENCIONAL','CONSTRUCCION DE ELECTRIFICACION NO CONVENCIONAL CON PANELES SOLARES EN MADERO LOCALIDAD DE LA ALMAZANA','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',2,'ACCION',15,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (44,'EL ZAPOTE HUERTA (ZAPOTE DE LA PENA)','ELECTRIFICACION','ELECTRIFICACION NO CONVENCIONAL','CONSTRUCCION DE ELECTRIFICACION NO CONVENCIONAL CON PANELES SOLARES EN MADERO LOCALIDAD DE ZAPOTE HUERTA','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',2,'ACCION',15,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (45,'GUAJINIQUIL','INFRAESTRUCTURA BASICA DEL SECTOR EDUCATIVO','TECHADO','CONSTRUCCION DE TECHADO EN AREA DE IMPARTICION DE EDUCACION FISICA EN ESCUELA PRIMARIA EN MADERO LOCALIDAD DE GUAJINIQUIL','EL AHIJADERO','CONTRATO',352,'M2',224,'$1,200,000.00',0.0,'$1,200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (46,'EL EJE','VIVIENDA','CUARTO PARA BANO','CONSTRUCCION DE CUARTO PARA BANO EN MADERO, LOCALIDAD DE EL EJE','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',5,'ACCION',50,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (47,'CORONILLAS','VIVIENDA','CUARTO PARA BANO','CONSTRUCCION DE CUARTO PARA BANO EN MADERO, LOCALIDAD DE CORONILLAS','CORONILLAS','ADMINISTRACION',5,'ACCION',50,'$240,000.00',0.0,'$240,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (48,'VILLA MADERO','VIVIENDA','CUARTO PARA BANO','CONSTRUCCION DE CUARTO PARA BANO EN MADERO, LOCALIDAD DE VILLA MADERO','VILLA MADERO','ADMINISTRACION',10,'ACCION',50,'$420,000.00',0.0,'$420,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (49,'ACATEN','VIVIENDA','CUARTO PARA BANO','CONSTRUCCION DE CUARTO PARA BANO EN MADERO,LOCALIDAD DE ACATEN','ACATEN','ADMINISTRACION',5,'ACCION',50,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (50,'SINDA','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE SINDA','SINDA','ADMINISTRACION',10,'ACCION',31,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (51,'EL AHIJADERO','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE EL AHIJADERO','EL AHIJADERO','ADMINISTRACION',10,'ACCION',50,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (52,'CUINDORA','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE LA CUINDORA','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',15,'ACCION',75,'$300,000.00',0.0,'$300,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (53,'SANTA CATARINA','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE SANTA CATARINA','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',5,'ACCION',40,'$100,000.00',0.0,'$100,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (54,'EL EJE','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE EL EJE','SAN DIEGO CURUCUPATZEO','ADMINISTRACION',10,'ACCION',75,'$200,000.00',0.0,'$200,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (55,'RANCHO DE PORUAS (LA TARJEA)','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE RANCHO DE PORUAS (LA TARJEA)','VILLA MADERO','ADMINISTRACION',10,'ACCION',100,'$134,000.00',0.0,'$134,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (56,'ZIPARAPIO EL BAJO','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE ZIPARAPIO EL BAJO','VILLA MADERO','ADMINISTRACION',20,'ACCION',100,'$250,000.00',0.0,'$250,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (57,'LAGUNA SECA','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE LAGUNA SECA','VILLA MADERO','ADMINISTRACION',10,'ACCION',75,'$150,000.00',0.0,'$150,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (58,'PUENTE CORAZA (EL ENCINO DE LAS CHICAS)','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE PUENTE CORAZA','VILLA MADERO','ADMINISTRACION',10,'ACCION',75,'$136,000.00',0.0,'$136,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (59,'SAN PEDRO PIEDRAS GORDAS','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE SAN PEDRO PIEDRAS GORDAS','VILLA MADERO','ADMINISTRACION',10,'ACCION',60,'$136,000.00',0.0,'$136,000.00',0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (60,'MUNICIPIO','INDIRECTOS','INDIRECTOS','INDIRECTOS','MUNICIPIO','ADMINISTRACION',1,'PROGRAMA',7633,700000.0,0.0,700000.0,0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (61,'ACATEN','VIVIENDA','PISO FIRME','CONSTRUCCION DE  PISO FIRME EN MADERO, LOCALIDAD DE ACATEN','ACATEN','ADMINISTRACION',15,'ACCION',75,190785.0,0.0,190785.0,0.0);
INSERT INTO "obras_obra" ("id","col_comunidad","rubro","subclasificacion","nombre_obra","tenencia","modalidad_ejecucion","metas_cantidad","metas_unidad","metas_beneficiarios","costo_total","inv_estatal","fism","inv_federal") VALUES (62,'MUNICIPIO','PRODIM','PRODIM','PRODIM','MUNICIPIO','ADMINISTRACION',1,'PROGRAMA',7633,500000.0,0.0,500000.0,0.0);
COMMIT;
